/* Generated by cbindgen */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef void* JsonParser;

JsonParser *json_parser_new(const char *path);

int json_parser_get_string(JsonParser handle,
                           const char *key,
                           char *output,
                           uintptr_t output_len);

void json_parser_free(JsonParser handle);
